routes/web.php
        Route::get('/checkout_ajax', 'CheckoutController@checkout_ajax')->name('checkout_ajax');
        Route::get('/shipping_ajax', 'CheckoutController@shipping_ajax')->name('shipping_ajax');
        Route::get('/shipping_ajax/single/{id}/{zip}', 'CheckoutController@shippingAjaxSingle')->name('shipping_ajax.single');

        Route::get('/check_zipcode', 'CheckoutController@check_zipcode')->name('check_zipcode');

        Route::post('/checkout_chat_ajax', 'CheckoutController@checkout_chat_ajax')->name('checkout_chat_ajax');
        Route::get('/wishlist-ajax', 'CheckoutController@wishlist_ajax')->name('wishlist-ajax');
        Route::get('/wishlist', 'CheckoutController@wishlist')->name('wish-list');
        Route::get('/wishlish_delete/{id}', 'CheckoutController@wishlish_delete')->name('wishlish_delete');

        Route::get('/checkout_ajax_qty/', 'CheckoutController@checkout_ajax_qty')->name('checkout_ajax_qty');
        Route::get('/checkout_delete/{id}', 'CheckoutController@checkout_delete')->name('checkout_delete');
        Route::get('/buyer_login_id/{seller}/{product}', 'HomeController@buyer_login')->name('buyer_login_id');
        Route::get('/add_check_out/{seller}/{product}/{price}/{last_segment}', 'HomeController@buyer_login')->name('add_check_out');
        Route::get('/buyer_signup', 'HomeController@buyer_signup')->name('buyer_signup');
        Route::post('stripe', 'CheckoutController@stripePost')->name('stripe.post');

        Route::post('/checkout-single-post','CheckoutController@checkoutSingle')->name('checkout.single.post');

        Route::get('/contact-us', 'HomeController@contact_us')->name('contact-us');
        Route::post('/contact-us-submit', 'HomeController@contact_us_submit')->name('contact-us-submit');
        Route::get('/profile/{id}', 'HomeController@profile')->name('profile');

    });


});



Route::middleware(['auth', 'admin'])->group(function () {
   Route::get('users-list', [UserController::class, 'getusers'])->name('users');

   Route::namespace('App\Http\Controllers\Admin')->group(function () {

    Route::resource('category', CategoryController::class);
    Route::resource('sub-category', SubCategoryController::class);
    Route::resource('brand', BrandController::class);
    Route::post('/brand-attahment/upload/{type}', 'BrandController@uploadAttachment')->name('brand.attachment.upload');


    // Seller Packages
    Route::get('packages', 'SellerPackageController@index')->name('seller.packages');
    Route::get('packages/add', 'SellerPackageController@create')->name('seller.packages.create');
    Route::delete('packages/delete/{package}', 'SellerPackageController@destroy')->name('seller.packages.destroy');
    Route::get('packages/{sellerPackage}/edit', 'SellerPackageController@edit')->name('seller.packages.edit');
    Route::get('packages/{sellerPackage}/detail', 'SellerPackageController@show')->name('seller.packages.detail');
    Route::post('packages/store', 'SellerPackageController@store')->name('seller.packages.store');
    Route::post('packages/{sellerPackage}/update', 'SellerPackageController@update')->name('seller.packages.update');
    Route::delete('packages/{sellerPackage}/delete', 'SellerPackageController@destroy')->name('seller.packages.delete');


    Route::get('/newsletter', 'HomeController@Newsletterindex')->name('newsletters.index');
    Route::resource('website-banners', PageBannerController::class);

    //ad pacakges
    Route::get('ads-banner-packages', 'AdsPackageController@index')->name('ad-packages');
    Route::get('ads-banner-packages/add', 'AdsPackageController@create')->name('ad-packages.create');
    Route::delete('ads-banner-packages/delete/{id}', 'AdsPackageController@destroy')->name('ad-packages.destroy');
    Route::get('ads-banner-packages/{eventPackages}/edit', 'AdsPackageController@edit')->name('ad-packages.edit');
    Route::get('ads-banner-packages/{eventPackages}/detail', 'AdsPackageController@show')->name('ad-packages.detail');
    Route::post('ads-banner-packages/store', 'AdsPackageController@store')->name('ad-packages.store');
    Route::post('ads-banner-packages/{eventPackages}/update', 'AdsPackageController@update')->name('ad-packages.update');
    Route::get('ads-banner-packages/{eventPackages}/delete', 'AdsPackageController@destroy')->name('ad-packages.delete');

    // Route::get('ads-banner-packages/{packageId}/buyForm', 'AdsPackageController@buyAdPackageForm')->name('buy-ad-package-form');
    // Route::post('ads-banner-packages/buy', 'AdsPackageController@buyAdPackage')->name('buy-ad-package-store');

    Route::get('warehouse-sellers', 'WarehouseController@SellerWearhouse')->name('warehouse.index.seller');

    Route::resource('testimonials', TestimonialController::class);
    Route::post('/testimonials-attahment/upload/{type}', 'TestimonialController@uploadAttachment')->name('testimonials.attachment.upload');
    Route::get('/testimonials-delete/{id}', 'TestimonialController@destroy')->name('testimonials.delete');

    //not in use
    Route::resource('subscription', SubscriptionController::class);

    Route::get('contacts-listing', 'HomeController@getcontactus')->name('getcontactus');
    Route::get('contacts-delete/{id}', 'HomeController@contactsdelete')->name('contact-delete');

    Route::get('settings', 'SettingController@index')->name('settings');
    Route::post('settings/{setting}/update', 'SettingController@update')->name('settings.update');

    });

});







Route::prefix('admin')->group(function () {
    Route::namespace('App\Http\Controllers\Admin')->group(function () {
        Route::middleware('auth:admin')->group(function () {
            Route::get('/', 'HomeController@index')->name('admin.dashboard');


            Route::resource('seller', SellerProductController::class);
            Route::resource('financial_statement', SellerfinancialContoller::class);
            Route::get('transfer/{id}', 'SellerfinancialContoller@transfer')->name('financial_statement.transfer');
            Route::resource('auction', AuctionProductController::class);
            Route::resource('trading', TradingProductController::class);



            Route::post('/page-banner-attahment/upload/{type}', 'PageBannerController@uploadAttachment')->name('page.banner.upload');
            Route::post('/category-attahment/upload/{type}', 'CategoryController@uploadAttachment')->name('category.attachment.upload');
            // Route::post('/product-attahment/upload/{type}', 'ProductController@uploadAttachment')->name('product.attachment.upload');
            // Route::get('/product/status/update/{product}/{status}', 'ProductController@updateStatus')->name('products.update.status');
            // Route::get('/order_item/status/update/{order_item}/{status}', 'OrderItemController@updateStatus')->name('order_items.update.status');
            // Route::get('/chat', 'ChatController@admin_chat')->name('chat');
            Route::get('/user/status/update/{user}/{status}', 'SellerProductController@updatestatus')->name('user.update.status');
            // Route::get('seller_user', 'SellerProductController@getusers')->name('users.seller');
            Route::get('/order/{flag}', 'OrderController@index')->name('order.index');
            Route::get('/order_print', 'OrderController@order_print')->name('order_print');
            Route::get('buyer_user', 'SellerProductController@buyer_user')->name('users.buyer');
            Route::get('maketrade', 'SellerProductController@maketrade')->name('maketrade.admin');
            Route::get('/maketrade-detail/{request_product_id}/{user_id}/{maketradeDetail}', 'SellerProductController@maketradeDetail')->name('maketrade.detail.admin');
            Route::get('/bid_list_admin', 'OrderItemController@bid_list_admin')->name('bid.list.admin');

            Route::get('trade-price', 'TradingProductController@trade_price')->name('trade-price');
            Route::put('trade_update/{id}', 'TradingProductController@trade_update')->name('trade_update');
            //user





            Route::get('order-disputes/{order_id}', [App\Http\Controllers\Admin\DisputeController::class ,'index'])->name('disputes.index.admin');
            Route::get('disputes',[App\Http\Controllers\Admin\DisputeController::class ,'list'])->name('dispute.list.admin');
            Route::get('disputes-show/{dispute}',[App\Http\Controllers\Admin\DisputeController::class ,'show'])->name('dispute.show.admin');
            Route::get('disputes-change-status/{dispute}/{status}',[App\Http\Controllers\Admin\DisputeController::class ,'ChangeStatus'])->name('dispute.change.status.admin');





        });
    });

});

Route::prefix('seller')->group(function () {
    Route::namespace('App\Http\Controllers\Admin')->group(function () {
        Route::middleware('auth:seller')->group(function () {
            Route::resource('seller_warehouse', WarehouseController::class);
            Route::get('connect', 'SellerfinancialContoller@connect')->name('financial_statement.connect');

            Route::get('/', 'HomeController@index')->name('seller_dashboard');
            Route::resource('seller_seller', SellerProductController::class);
            Route::resource('seller_auction', AuctionProductController::class);
            Route::resource('seller_trading', TradingProductController::class);
            Route::resource('seller_category', CategoryController::class);
            Route::resource('seller_sub-category', SubCategoryController::class);



            Route::post('/seller_category-attahment/upload/{type}', 'CategoryController@uploadAttachment')->name('seller_category.attachment.upload');
            Route::post('/seller_product-attahment/upload/{type}', 'ProductController@uploadAttachment')->name('seller_product.attachment.upload');
            Route::get('/seller_chat', 'ChatController@index')->name('seller_chat');

app/Models/PageBanner.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes; //add this line


class PageBanner extends Model
{
    use HasFactory;
    use SoftDeletes; //add this line

    protected $table = "page_images";
    protected $guarded = [];

 
}

app/Http/Controllers/Admin/PageBannerController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Brand;
use App\Models\PageBanner;
use Illuminate\Support\Str;
use DB;

class PageBannerController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        
        $banners = PageBanner::latest()->get();
        return view('pages.admin.page_banners.index', compact('banners'));
    }

    public function create()
    {
        return view('pages.admin.page_banners.create');
    }
    public function edit($id)
    {
        $PageBanner = PageBanner::where('id',$id)->first();
        return view('pages.admin.page_banners.edit',compact('PageBanner'));
    }
    public function destroy($id)
    {
        $banner = PageBanner::findorfail($id);
        $banner->delete();
        return response()->json(['msg' => 'Banner deleted successfully!!']);
    }

    public function store(Request $request)
    {

        $request->validate([
            'page' => 'required',
            'position' => 'required',
            'image_url' => 'required | url',
            'banner_image' => 'required',
        ]);

        $data = $request->except('_token');
        DB::beginTransaction();
        try {
        
            PageBanner::create($data);

            DB::commit();
            return response()->json(['msg' => 'Banner has been inserted successfully'], 200);
        } catch (\Exception $e) {
            DB::rollback();
            return response()->json(['msg' => $e->getMessage()], 500);

        }
    }
    public function update(Request $request,$id)
    {
        $PageBanner = PageBanner::find($id);

        $request->validate([
            'page' => 'required',
            'position' => 'required',
            'image_url' => 'required | url',
        ]);

        $data = $request->except('_token');
        if($request->banner_image == null){
            unset($data['banner_image']);
        }

        DB::beginTransaction();
        try {
            $PageBanner->update($data);

            DB::commit();
            return response()->json(['msg' => 'Brand has been updated successfully'], 200);
        } catch (\Exception $e) {
            DB::rollback();
            return response()->json(['msg' => $e->getMessage()], 500);

        }
    }

    public function uploadAttachment(Request $request, $type)
    {
        $image = "banner";
        if ($type == 'banner') {
            $request->validate([
                'banner' => 'required|image',
            ]);
        } else {
            $request->validate([
                'image' => 'required|image',
            ]);
            $image = "image";
        }

        $fileName = $request->$image->store('public/page_banners');
        $fileName = Str::after($fileName, 'public/');
        return response(['msg' => 'image uploaded successfully!!', 'file_name' => $fileName]);
    }
  

}

resources/views/pages/admin/page_banners/create.blade.php
@extends('layout.default')
@php
    $page_breadcrumbs=[
    [
    'page'=>route('dashboard'),
    'title'=>'dashboard'
    ],
    [
    'page'=>route('website-banners.index'),
    'title'=>'Add Banner'
    ]
    ];
@endphp
@section('styles')
    <link rel="stylesheet" href="{{asset('css/jquery-ui.css')}}">
    <style>
        .label-centered-field {
            display: flex;
            align-items: center;
            margin-top: 8px;
        }

        .time-off-action-row label {
            visibility: hidden;
        }

        .time-off-action-row a {
            display: table-cell;
            padding: 5px;
        }

        .day-activities {
            display: flex;
            align-items: center
        }

        .switch-right-side {
            margin-left: 5px;
        }

        #map {
            height: 400px;
            /* The height is 400 pixels */
            width: 100%;
            /* The width is the width of the web page */
        }

        #reset_location {
            margin-top: 5px;
        }
    </style>
@endsection
@section('content')
    <div class="row">
        <div class="col-md-12">
            <div class="card card-custom flex-wrap border-0 pt-6 pb-0">
                <form class="form" id="form" method="POST" action="{{route('website-banners.store')}}">
                    @csrf
                  
                    <div class="card card-custom card-sticky" id="kt_page_sticky_card">
                        <div class="card-header" style="">
                            <div class="card-title col-md-9">
                                <h3 class="card-label">New Banner
                                    <!-- <i class="mr-2"></i> -->
                                    <!-- <small class="">try to scroll the page</small> -->
                                </h3>
                            </div>
                            <div class="card-toolbar">
                                <a href="{{route('website-banners.index')}}" class="btn btn-secondary font-weight-bold mr-2">
                                    <i class="ki ki-long-arrow-back icon-xs"></i>Cancel
                                </a>
                                <button type="submit" class="btn btn-primary font-weight-bolder">Save Banner</button>
                            </div>


                        </div>
                        <div class="card-body">
                            <div class="row">
                                <div class="col-md-8">

                                    <div class="form-group">
                                        <label for="page">Page</label>
                                        <select name="page" id="page" class="form-control" required>
                                            <option value=""> Select Page Name </option>
                                            <option value="home"> Home </option>
                                            <option value="products"> Products </option>
                                        </select>
                                    </div>

                                    <div class="form-group">
                                        <label for="position">Position</label>
                                        <select name="position" id="position" class="form-control" required>
                                            <option value=""> Select Position </option>
                                            <option value="top"> Top </option>
                                            <option value="left-1"> Left-1 </option>
                                            <option value="left-2"> Left-2 </option>
                                        </select>
                                    </div>

                                    <div class="form-group">
                                        <label for="image_url">Image URL</label>
                                        <input type="url" name="image_url" id="image_url" class="form-control">
                                    </div>

                                </div>
                               <div class="col-md-4">
                                   <div class="flex-grow-1" style="position: relative;">
                                       <div class="form-group">
                                           <!-- <h1 class="image-upload-msg">Banner Image</h1> -->
                                           <div class="dropzone dropzone-default dropzone-success" id="banner_image">
                                               <div class="dropzone-msg dz-message needsclick">

                                                       <h3 class="dropzone-msg-title">Drop files here or click to upload.</h3>
                                                       <span class="dropzone-msg-desc">Only images are allowed for upload</span>

                                               </div>
                                           </div>
                                       </div>
                                   </div>
                                   <input type="hidden" name="banner_image" id="banner_image">
                           </div>


                        </div>
                    </div>

                </form>
            </div>

        </div>
    </div>
@endsection
@section('scripts')
    <script src="{{asset('js/jquery-ui.js')}}"></script>
    <script>
        const name = {
            validators: {
                notEmpty: {
                    message: 'Enter is name'
                }
            }
        }


        const bv = FormValidation.formValidation(

            document.getElementById('form'), {
                fields: {
                    page: {
                        validators: {
                            notEmpty: {
                                message: 'Page Name is required'
                            }
                        }
                    },
                    position: {
                        validators: {
                            notEmpty: {
                                message: 'Position is required'
                            }
                        }
                    },

                }, plugins: {
                    trigger: new FormValidation.plugins.Trigger(),
                    // Bootstrap Framework Integration
                    bootstrap: new FormValidation.plugins.Bootstrap(),
                    // Validate fields when clicking the Submit button
                    submitButton: new FormValidation.plugins.SubmitButton(),
                }
            }
        ).on('core.form.valid', function () {
            // Send the form data to back-end
            // You need to grab the form data and create an Ajax request to send them
            // Get the form instance
            var $form = $('#form');
            // Get the BootstrapValidator instance
            let method = $form.attr('method');
            let url = $form.attr('action');
            let data = new FormData(document.getElementById('form'));
            submitFormAjax(method, url, data, function (res) {

                successAlert(res.msg);
                $('#form').trigger('reset');
                $('.dz-complete').remove();
                $('.needsclick').show();


                window.location.href = "{{route('website-banners.index')}}";

            }, function (jqXHR) {
                let errors = jqXHR.responseJSON.errors;
                let erMsgs = ``;
                $.each(Object.keys(errors), function (i, v) {
                    erMsgs += `<p>${i + 1}-${errors[v][0]}</p>`;
                })
                errorAlert(erMsgs);
            }, bv);
        });


        function readURL(input, id) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();

                reader.onload = function (e) {
                    $(id)
                        .attr('src', e.target.result);
                    $('.profile-icon').hide();
                    $(id).show();
                };
                reader.readAsDataURL(input.files[0]);
            }
        }

        $('#banner_image').dropzone({
            url: "{{route('page.banner.upload','banner')}}", // Set the url for your upload script location
            paramName: "banner", // The name that will be used to transfer the file
            maxFiles: 1,
            maxFilesize: 10, // MB
            // addRemoveLinks: true,
            acceptedFiles: "image/*",
            sending: function (file, xhr, formData) {
                formData.append("_token", "{{ csrf_token() }}");
            },
            accept: function (file, done) {
                done();
            },
            success: function (http) {
                let data = jQuery.parseJSON(http.xhr.response)
                $('.dz-complete').html('<div class="dropzone-msg dz-message needsclick"><h3 class="dropzone-msg-title">Drop files here or click to upload.</h3> <span class="dropzone-msg-desc">Only images are allowed for upload</span> </div>');

                $('[name=banner_image]').val(data.file_name);
                // $('#banner_image_val').val(data.file_name);

            }
        });

    </script>
@endsection

resources/views/pages/admin/page_banners/index.blade.php
@extends('layout.default')
@php
        $page_breadcrumbs=[[
        'page'=>route('dashboard'),
        'title'=>'dashboard'
        ],
        [
        'page'=>route('website-banners.index'),
        'title'=>'Page Banners'
        ]
        ];
@endphp
@section('styles')
    <link rel="stylesheet" href="{{asset('plugins/custom/datatables/datatables.bundle.css?v=7.0.4')}}">
@endsection
@section('content')
    @include('pages.message')
    <div class="card card-custom">
        <div class="card-header flex-wrap border-0 pt-6 pb-0">
            <div class="card-title">
                <h3 class="card-label">Page Banners List
                </h3>
            </div>
            <div class="card-toolbar" style="display: none">
                <a href="{{route('website-banners.create')}}" class="btn btn-primary font-weight-bolder font-size-sm mr-3 ">Add Banner</a>
            </div>
        </div>
        <div class="card-body">
            <!--begin: Search Form-->
            <!--begin::Search Form-->
            <table class="table table-separate table-head-custom table-checkable" id="kt_datatable">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>Page</th>
                    <th>Position</th>
                    <th>URL</th>
                    <th>Image</th>
                    <th>Actions</th>
                </tr>
                </thead>
                <tbody>
                @foreach($banners as $b)
                    <tr>
                        <td>{{$b->id}}</td>
                        <td>{{$b->page}}</td>
                        <td>{{$b->position}}</td>
                        <td>{{$b->image_url}}</td>
                        <td><img src="{{asset('/storage/'.$b->banner_image ?? '')}}" style="width:150px;max-height:150px;"></td>
                        <td>
                        <span style="overflow: visible; position: relative; width: 125px;">
                            <div class="dropdown dropdown-inline "> <a href="javascript:;"
                                                                       class="btn btn-sm btn-light btn-text-primary btn-icon mr-2"
                                                                       data-toggle="dropdown">
                                    <span class="svg-icon svg-icon-md"> <svg xmlns="http://www.w3.org/2000/svg"
                                                                             xmlns:xlink="http://www.w3.org/1999/xlink"
                                                                             width="24px" height="24px"
                                                                             viewBox="0 0 24 24" version="1.1">
                                            <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                                                <rect x="0" y="0" width="24" height="24"></rect>
                                                <path d="M5,8.6862915 L5,5 L8.6862915,5 L11.5857864,2.10050506 L14.4852814,5 L19,5 L19,9.51471863 L21.4852814,12 L19,14.4852814 L19,19 L14.4852814,19 L11.5857864,21.8994949 L8.6862915,19 L5,19 L5,15.3137085 L1.6862915,12 L5,8.6862915 Z M12,15 C13.6568542,15 15,13.6568542 15,12 C15,10.3431458 13.6568542,9 12,9 C10.3431458,9 9,10.3431458 9,12 C9,13.6568542 10.3431458,15 12,15 Z"
                                                      fill="#000000"></path>
                                            </g>
                                        </svg> </span> </a>
                                <div class="dropdown-menu dropdown-menu-sm dropdown-menu-right">
                                    <ul class="navi flex-column navi-hover py-2">
                                        <li class="navi-header font-weight-bolder text-uppercase font-size-xs text-primary pb-2">
                                            Choose an action: </li>
                                        <li class="navi-item">
                                            <a href="{{route('website-banners.edit',$b->id)}}" class="navi-link">
                                                <span class="navi-icon">
                                                    <i class="la la-edit"></i>
                                                </span>
                                                <span class="navi-text">Edit</span>
                                            </a>
                                        </li>
                                         <li class="navi-item">
                                               <a href="javascript:void(0)"
                                                  onclick="deleteTableRecord('{{route('website-banners.destroy',$b->id)}}',$(this).closest('tr'))"
                                                  class="navi-link">
                                                   <span class="navi-icon">
                                                    <i class="la la-trash"></i>
                                                </span>
                                                   <span class="navi-text">Delete</span>
                                                   </i>
                                               </a>
                                        </li>

                                    </ul>
                                </div>
                            </div>
                        </span>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
    </div>


@endsection

{{-- Styles Section --}}
@section('styles')

@endsection

@section('scripts')
    <script src="{{ asset('plugins/custom/datatables/datatables.bundle.js?v=7.0.4') }}" type="text/javascript"></script>
    <script>
        var table = $('#kt_datatable');

        // begin first table
        table.DataTable({
            // DOM Layout settings
            dom: "<'row py-3'<'col-sm-12 col-md-6'l><'col-sm-12 col-md-6'f>>" +
                "<'row'<'col-sm-12 col-md-6'i><'col-sm-12 col-md-6'p>>" +
                "<'row py-3'<'col-sm-12'tr>>" +
                "<'row py-3'<'col-sm-12 col-md-6'l><'col-sm-12 col-md-6'f>>" +
                "<'row'<'col-sm-12 col-md-5'i><'col-sm-12 col-md-7'p>>", // read more: https://datatables.net/examples/basic_init/dom.html

            columnDefs: [{
                targets: -1,
                title: 'Actions',
                orderable: false,

            },
            ],
        });
    </script>
@endsection