routes/web.php
    Route::resource('testimonials', TestimonialController::class);
    Route::post('/testimonials-attahment/upload/{type}', 'TestimonialController@uploadAttachment')->name('testimonials.attachment.upload');
    Route::get('/testimonials-delete/{id}', 'TestimonialController@destroy')->name('testimonials.delete');

    //not in use
    Route::resource('subscription', SubscriptionController::class);

    Route::get('contacts-listing', 'HomeController@getcontactus')->name('getcontactus');
    Route::get('contacts-delete/{id}', 'HomeController@contactsdelete')->name('contact-delete');

    Route::get('settings', 'SettingController@index')->name('settings');
    Route::post('settings/{setting}/update', 'SettingController@update')->name('settings.update');

    });

});







Route::prefix('admin')->group(function () {
    Route::namespace('App\Http\Controllers\Admin')->group(function () {
        Route::middleware('auth:admin')->group(function () {
            Route::get('/', 'HomeController@index')->name('admin.dashboard');


            Route::resource('seller', SellerProductController::class);
            Route::resource('financial_statement', SellerfinancialContoller::class);
            Route::get('transfer/{id}', 'SellerfinancialContoller@transfer')->name('financial_statement.transfer');
            Route::resource('auction', AuctionProductController::class);
            Route::resource('trading', TradingProductController::class);



            Route::post('/page-banner-attahment/upload/{type}', 'PageBannerController@uploadAttachment')->name('page.banner.upload');
            Route::post('/category-attahment/upload/{type}', 'CategoryController@uploadAttachment')->name('category.attachment.upload');
            // Route::post('/product-attahment/upload/{type}', 'ProductController@uploadAttachment')->name('product.attachment.upload');
            // Route::get('/product/status/update/{product}/{status}', 'ProductController@updateStatus')->name('products.update.status');
            // Route::get('/order_item/status/update/{order_item}/{status}', 'OrderItemController@updateStatus')->name('order_items.update.status');
            // Route::get('/chat', 'ChatController@admin_chat')->name('chat');
            Route::get('/user/status/update/{user}/{status}', 'SellerProductController@updatestatus')->name('user.update.status');
            // Route::get('seller_user', 'SellerProductController@getusers')->name('users.seller');
            Route::get('/order/{flag}', 'OrderController@index')->name('order.index');
            Route::get('/order_print', 'OrderController@order_print')->name('order_print');
            Route::get('buyer_user', 'SellerProductController@buyer_user')->name('users.buyer');
            Route::get('maketrade', 'SellerProductController@maketrade')->name('maketrade.admin');
            Route::get('/maketrade-detail/{request_product_id}/{user_id}/{maketradeDetail}', 'SellerProductController@maketradeDetail')->name('maketrade.detail.admin');
            Route::get('/bid_list_admin', 'OrderItemController@bid_list_admin')->name('bid.list.admin');

            Route::get('trade-price', 'TradingProductController@trade_price')->name('trade-price');
            Route::put('trade_update/{id}', 'TradingProductController@trade_update')->name('trade_update');
            //user





            Route::get('order-disputes/{order_id}', [App\Http\Controllers\Admin\DisputeController::class ,'index'])->name('disputes.index.admin');
            Route::get('disputes',[App\Http\Controllers\Admin\DisputeController::class ,'list'])->name('dispute.list.admin');
            Route::get('disputes-show/{dispute}',[App\Http\Controllers\Admin\DisputeController::class ,'show'])->name('dispute.show.admin');
            Route::get('disputes-change-status/{dispute}/{status}',[App\Http\Controllers\Admin\DisputeController::class ,'ChangeStatus'])->name('dispute.change.status.admin');





        });
    });

});

Route::prefix('seller')->group(function () {
    Route::namespace('App\Http\Controllers\Admin')->group(function () {
        Route::middleware('auth:seller')->group(function () {
            Route::resource('seller_warehouse', WarehouseController::class);
            Route::get('connect', 'SellerfinancialContoller@connect')->name('financial_statement.connect');

            Route::get('/', 'HomeController@index')->name('seller_dashboard');
            Route::resource('seller_seller', SellerProductController::class);
            Route::resource('seller_auction', AuctionProductController::class);
            Route::resource('seller_trading', TradingProductController::class);
            Route::resource('seller_category', CategoryController::class);
            Route::resource('seller_sub-category', SubCategoryController::class);



            Route::post('/seller_category-attahment/upload/{type}', 'CategoryController@uploadAttachment')->name('seller_category.attachment.upload');
            Route::post('/seller_product-attahment/upload/{type}', 'ProductController@uploadAttachment')->name('seller_product.attachment.upload');
            Route::get('/seller_chat', 'ChatController@index')->name('seller_chat');
            Route::get('/seller_product/status/update/{product}/{status}', 'ProductController@updateStatus')->name('seller_products.update.status');
            Route::get('/seller_order/{flag}', 'OrderController@index')->name('seller_order.index');
            Route::get('/seller_order_print', 'OrderController@order_print')->name('seller_order_print');
            Route::get('/seller_order_item/status/update/{order_item}/{status}', 'OrderItemController@updateStatus')->name('seller_order_items.update.status');
            Route::get('maketrade', 'SellerProductController@maketrade')->name('maketrade');
            Route::get('/maketrade-detail/{request_product_id}/{user_id}/{maketradeDetail}', 'SellerProductController@maketradeDetail')->name('maketrade.detail');
            Route::get('/maketrade/status/update/{request_product_id}/{user_id}/{status}', 'SellerProductController@updateStatus_trade')->name('maketrade.update.status');
            Route::post('stripe_trade', 'TradingProductController@stripePost')->name('stripe_trade.post');
            Route::get('/bid_list_seller', 'OrderItemController@bid_list_seller')->name('bid.list.seller');

            Route::get('create-banner/{package_id}/{user_package_id}', 'AdsPackageController@createbanner')->name('saller-create-banner');
            Route::post('banner-store', 'AdsPackageController@bannerstore')->name('seller_banner.store');


            Route::get('package-renew', 'SellerPackageController@PackageRenew')->name('package-renew');
            Route::post('package-renew', 'SellerPackageController@PackageRenewUpdate')->name('package-renew.update');


            Route::get('order-disputes/{order_id}', [App\Http\Controllers\Admin\DisputeController::class ,'index'])->name('disputes.index.seller');
            Route::get('disputes',[App\Http\Controllers\Admin\DisputeController::class ,'list'])->name('dispute.list.seller');
            Route::get('disputes-show/{dispute}',[App\Http\Controllers\Admin\DisputeController::class ,'show'])->name('dispute.show.seller');




        });
    });

});
Route::prefix('buyer')->group(function () {
    Route::namespace('App\Http\Controllers\Admin')->group(function () {
        Route::middleware('auth:buyer')->group(function () {
            Route::get('/', 'HomeController@index')->name('buyer_dashboard');
            Route::get('/buyer_chat', 'ChatController@index')->name('buyer_chat');
            Route::get('/buyer_order/{flag}', 'OrderController@index')->name('buyer_order.index');
            Route::get('/buyer_review', 'ReviewController@index')->name('buyer_review.index');
            Route::get('/buyer_order_print', 'OrderController@order_print')->name('buyer_order_print');
            Route::post('/store', 'ReviewController@store')->name('review.store');
            Route::get('/bid_list', 'OrderItemController@bid_list')->name('bid.list');
            Route::get('/buyer_order_item/status/update/{order_item}/{status}', 'OrderItemController@updateStatus')->name('buyer_order_items.update.status');

            // RequestTradeProduct
            Route::get('request-trading', 'RequestTradeProductController@index')->name('request.trading');
            Route::get('request-trading/add/{id}', 'RequestTradeProductController@create')->name('request.trading.create');
            Route::delete('request-trading/delete/{id}', 'RequestTradeProductController@destroy')->name('request.trading.destroy');
            Route::get('request-trading/{id}/edit', 'RequestTradeProductController@edit')->name('request.trading.edit');
            Route::get('request-trading/{id}/detail', 'RequestTradeProductController@show')->name('request.trading.detail');
            Route::post('request-trading/store', 'RequestTradeProductController@store')->name('request.trading.store');
            Route::post('request-trading/update', 'RequestTradeProductController@update')->name('request.trading.update');
            Route::get('request-trading/{id}/delete', 'RequestTradeProductController@destroy')->name('request.trading.delete');
            Route::post('/seller_product-attahment/upload/{type}', 'ProductController@uploadAttachment')->name('request.trading.attachment.upload');


            Route::get('order-disputes/{order_id}', [App\Http\Controllers\Admin\DisputeController::class ,'index'])->name('disputes.index.buyer');
            Route::get('dispute-form/{order_id}', [App\Http\Controllers\Admin\DisputeController::class ,'create'])->name('disputes.create.buyer');
            Route::post('dispute-form/submit', [App\Http\Controllers\Admin\DisputeController::class ,'store'])->name('disputes.store.buyer');


            Route::get('/checkout-list','HomeController@checkoutList')->name('checkout.list');


        });
    });

app/Models/Dispute.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Dispute extends Model
{
    use HasFactory;

    protected $fillable = [

        'order_id',
        'name',
        'email',
        'message',
        'status',
        'seller_id',
        'user_id'
    ];

    public function seller_name()
    {
        return $this->belongsTo(User::class,'seller_id','id');
    }

    public function buyer_name()
    {
        return $this->belongsTo(User::class,'user_id','id');
    }

    public function order()
    {
        return $this->belongsTo(Order::class,'order_id','id');
    }


}

app/Http/Controllers/Admin/DisputeController.php
<?php

namespace App\Http\Controllers\admin;

use App\Models\Dispute;
use App\Models\order_item;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use DB;


class DisputeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function list()
    {

        if(Auth()->guard('seller')->check()) {
            $data['disputes'] = Dispute::where('seller_id',auth()->user()->id)->get();
        }
        else{
            $data['disputes'] = Dispute::all();
        }
        return view('pages.admin.disputes.index',$data);
    }

     public function index($order_id)
    {

        if (Auth()->guard('buyer')->check()) {
            $data['disputes'] = Dispute::where('user_id',auth()->user()->id)->where('order_id',$order_id)->get();
        }
        elseif (Auth()->guard('seller')->check()) {
            $data['disputes'] = Dispute::where('seller_id',auth()->user()->id)->where('order_id',$order_id)->get();
        }
        else{
            $data['disputes'] = Dispute::where('order_id',$order_id)->get();
        }
        return view('pages.admin.disputes.index',$data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create($order_id)
    {
        $data['dispute'] = Dispute::where('user_id',auth()->user()->id)->where('order_id',$order_id)->with(['seller_name'])->first();
        $data['order_id'] = $order_id;
        return view('pages.admin.disputes.create',$data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // dd($request->all());
        try {
            DB::beginTransaction();
            $dispute = Dispute::where('order_id',$request->order_id)->where('user_id',$request->user_id)->first();
            if($dispute !== null){
                $dispute->message = $request->message;
                $dispute->save();
                DB::commit();
                return response()->json(['msg' => 'Message has been changed.', 'code' => 200]);
            }
            else{
                $input = $request->all();
                $input['seller_id'] = order_item::where('order_id',$request->order_id)->pluck('seller_id')->first();
                unset($input['_token']);
                Dispute::create($input);
                DB::commit();
                return response()->json(['msg' => 'Dispute has been added.', 'code' => 200]);

            }

        } catch (\Throwable $th) {
            DB::rollback();
            return response()->json(['msg' => $th->getMessage(), 'code' => 500]);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Dispute  $dispute
     * @return \Illuminate\Http\Response
     */
    public function show(Dispute $dispute)
    {
        $data['dispute'] = $dispute; 
        return view('pages.admin.disputes.show',$data);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Dispute  $dispute
     * @return \Illuminate\Http\Response
     */
    public function edit(Dispute $dispute)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Dispute  $dispute
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Dispute $dispute)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Dispute  $dispute
     * @return \Illuminate\Http\Response
     */
    public function destroy(Dispute $dispute)
    {
        //
    }

    public function ChangeStatus(Dispute $dispute, $status)
    {
        // dd($dispute,$status);
        try {
            DB::beginTransaction();
            if($status === 'refunded') {
             $order = order_item::where('order_id', $dispute->order_id)->get();                      
                $stripe = new \Stripe\StripeClient(env('STRIPE_SECRET'));
                  $stripe->refunds->create([
                    'charge' => $order[0]['charge_id'],
                  ]);
                  $dispute->status = 'refunded';
                  $dispute->save();

                  $notification = 'Payment has been refunded';
                  foreach ($order as $key => $value) {
                    $value->update(['status' => 'dispute']);
                  }
                  
            }
            elseif($status === 'processing'){
                $dispute->status = 'processing';
                $dispute->save();
                $notification = 'Dispute status has been changed';
            }
            elseif($status === 'cancel'){
                $dispute->status = 'cancel';
                $dispute->save();
                $notification = 'Dispute status has been changed';
            }
            DB::commit();
            return redirect()->back()->with('alert-success', $notification);
        }
         catch (\Throwable $th) {
            $notification = array(
                'message' => $th->getMessage(),
                'alert-type' => 'error'
            );
            DB::rollback();
            return redirect()->back()->with('alert-danger', $th->getMessage());
        }

        
    }
}

resources/views/pages/admin/disputes/create.blade.php
@extends('layout.default')
@section('styles')
<link rel="stylesheet" href="{{asset('css/jquery-ui.css')}}">
<link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.css" rel="stylesheet">
<style>
    .label-centered-field {
        display: flex;
        align-items: center;
        margin-top: 8px;
    }

    .time-off-action-row label {
        visibility: hidden;
    }

    .time-off-action-row a {
        display: table-cell;
        padding: 5px;
    }

    .day-activities {
        display: flex;
        align-items: center
    }

    .switch-right-side {
        margin-left: 5px;
    }

    #map {
        height: 400px;
        /* The height is 400 pixels */
        width: 100%;
        /* The width is the width of the web page */
    }

    #reset_location {
        margin-top: 5px;
    }
</style>
@endsection
@section('content')

<div class="row">
    <div class="col-md-12">
        <div class="card card-custom flex-wrap border-0 pt-6 pb-0">
            <form class="form" id="form" method="POST" action="{{ route('disputes.store.buyer')}}">
                @csrf
                <div class="card card-custom card-sticky" id="kt_page_sticky_card">
                    <div class="card-header" style="">
                        <div class="card-title col-md-8">
                            <h3 class="card-label">Dispute Form
                                <!-- <i class="mr-2"></i> -->
                                <!-- <small class="">try to scroll the page</small> -->
                            </h3>
                        </div>
                        <div class="card-toolbar">
                            <a href="{{route('sub-category.index')}}" class="btn btn-secondary font-weight-bold mr-2">
                                <i class="ki ki-long-arrow-back icon-xs"></i>
                                Cancel
                            </a>
                            <button type="submit" class="btn btn-primary font-weight-bolder">Save Dispute</button>
                        </div>


                    </div>
                    <div class="card-body">
                        <div class="row">

                            @if($dispute != null)
                            <div class="col-md-8">
                               <div class="form-group">
                                   <label for="status">Status</label>
                                   <input type="text" required id="status" value="{{  $dispute->status  }}"
                                       class="form-control" name="status" readonly>
                               </div>
                           </div>
                            @endif

                            <div class="col-md-8">

                                <div class="form-group">
                                    <label for="name">Your Name</label>
                                    <input type="text" value="{{ auth()->user()->name  }}" required id="name"
                                        class="form-control" name="name" readonly>
                                </div>

                            </div>

                            <div class="col-md-8">
                                <div class="form-group">
                                    <label for="email">Your Email</label>
                                    <input type="email" required id="email" value="{{ auth()->user()->email  }}"
                                        class="form-control" name="email" readonly>
                                </div>
                            </div>
                        </div>
                        <input type="hidden" name="order_id" value="{{ $order_id }}">
                        <input type="hidden" name="user_id" value="{{ auth()->user()->id }}">
                        

                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label for="message">Message</label>
                                    <textarea required id="message" class="form-control"
                                        name="message">{{ ($dispute != null) ? $dispute->message : '' }}</textarea>
                                </div>
                            </div>
                        </div>



                    </div>
                </div>

            </form>
        </div>

    </div>
</div>
@endsection
@section('scripts')
<script src="{{asset('js/jquery-ui.js')}}"></script>
<script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.js"></script>

<script>
    const message = {
            validators: {
                notEmpty: {
                    message: 'Enter is name'
                }
            }
        }

        const bv = FormValidation.formValidation(

            document.getElementById('form'), {
                fields: {
                    message: {
                        validators: {
                            notEmpty: {
                                message: 'Message Feild is Required'
                            }
                        }
                    },

                }, plugins: {
                    trigger: new FormValidation.plugins.Trigger(),
                    // Bootstrap Framework Integration
                    bootstrap: new FormValidation.plugins.Bootstrap(),
                    // Validate fields when clicking the Submit button
                    submitButton: new FormValidation.plugins.SubmitButton(),
                }
            }
        ).on('core.form.valid', function () {
            // Send the form data to back-end
            // You need to grab the form data and create an Ajax request to send them
            // Get the form instance
            var $form = $('#form');
            // Get the BootstrapValidator instance
            let method = $form.attr('method');
            let url = $form.attr('action');
            let data = new FormData(document.getElementById('form'));
            submitFormAjax(method, url, data, function (res) {
                if (res.code == 200) {
                successAlert(res.msg);
                $('.dz-complete').remove();
                $('.needsclick').show();
                window.location.href = "{{route('disputes.create.buyer',$order_id)}}";
                }
                else{
                    errorAlert('Something went wrong');
                }


            }, function (jqXHR) {
                let errors = jqXHR.responseJSON.errors;
                let erMsgs = ``;
                $.each(Object.keys(errors), function (i, v) {
                    erMsgs += `<p>${i + 1}-${errors[v][0]}</p>`;
                })
                errorAlert(erMsgs);
            }, bv);
        });


        function readURL(input, id) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();

                reader.onload = function (e) {
                    $(id)
                        .attr('src', e.target.result);
                    $('.profile-icon').hide();
                    $(id).show();
                };
                reader.readAsDataURL(input.files[0]);
            }
        }



</script>
@endsection

resources/views/pages/admin/disputes/index.blade.php
@extends('layout.default')

@section('styles')
<link rel="stylesheet" href="{{ asset('plugins/custom/datatables/datatables.bundle.css?v=7.0.4') }}">
@endsection
@section('content')
@include('pages.message')
<div class="card card-custom">
    <div class="card-header flex-wrap border-0 pt-6 pb-0">
        <div class="card-title">
            <h3 class="card-label">Disputes List
            </h3>
        </div>

    </div>
    <div class="card-body">

        <!--begin: Search Form-->
        <!--begin::Search Form-->
        <table class="table table-separate table-head-custom table-checkable" id="kt_datatable">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Order ID</th>
                    <th>Buyer Name</th>
                    <th>Buyer Email</th>
                    <th>Status</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>

                @foreach ($disputes as $d)
                <tr>
                    <td>{{ $d->id }}</td>
                    <td>{{ $d->order_id }}</td>
                    <td>{{ $d->name }}</td>
                    <td>{{ $d->email }}</td>
                    <td class="text-uppercase font-weight-bold">{{ $d->status }}</td>
                    <td>
                        <span style="overflow: visible; position: relative; width: 125px;">
                            <div class="dropdown dropdown-inline "> <a href="javascript:;" class="btn btn-sm btn-light btn-text-primary btn-icon mr-2" data-toggle="dropdown">
                                    <span class="svg-icon svg-icon-md"> <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="24px" height="24px" viewBox="0 0 24 24" version="1.1">
                                            <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
                                                <rect x="0" y="0" width="24" height="24"></rect>
                                                <path d="M5,8.6862915 L5,5 L8.6862915,5 L11.5857864,2.10050506 L14.4852814,5 L19,5 L19,9.51471863 L21.4852814,12 L19,14.4852814 L19,19 L14.4852814,19 L11.5857864,21.8994949 L8.6862915,19 L5,19 L5,15.3137085 L1.6862915,12 L5,8.6862915 Z M12,15 C13.6568542,15 15,13.6568542 15,12 C15,10.3431458 13.6568542,9 12,9 C10.3431458,9 9,10.3431458 9,12 C9,13.6568542 10.3431458,15 12,15 Z" fill="#000000"></path>
                                            </g>
                                        </svg> </span> </a>
                                <div class="dropdown-menu dropdown-menu-sm dropdown-menu-right">
                                    <ul class="navi flex-column navi-hover py-2">
                                        <li class="navi-header font-weight-bolder text-uppercase font-size-xs text-primary pb-2">
                                            Choose an action: </li>
                                        @if(Auth::guard('admin')->check())
                                        <li class="navi-item">
                                            <a href="{{ route('dispute.show.admin',$d->id)}}" class="navi-link">
                                                <span class="navi-icon">
                                                    <i class="la la-edit"></i>
                                                </span>
                                                <span class="navi-text">View</span>
                                            </a>
                                        </li>
                                       @if($d->status !== 'refunded') 
                                       <li class="navi-item">
                                            <a href="{{ route('dispute.change.status.admin',[$d->id,'cancel'])}}" class="navi-link">
                                                <span class="navi-icon">
                                                    <i class="la la-edit"></i>
                                                </span>
                                                <span class="navi-text">Cancel</span>
                                            </a>
                                        </li>
                                        @endif

                                        @if($d->status === 'pending')
                                        <li class="navi-item">
                                            <a href="{{ route('dispute.change.status.admin', [$d->id, 'processing'])   }}" class="navi-link">
                                                <span class="navi-icon">
                                                    <i class="la la-edit"></i>
                                                </span>
                                                <span class="navi-text">In Process</span>
                                            </a>
                                        </li>
                                        @elseif($d->status === 'processing')
                                        <li class="navi-item">
                                            <a href="{{ route('dispute.change.status.admin', [$d->id , 'refunded'])  }}" class="navi-link">
                                                <span class="navi-icon">
                                                    <i class="la la-edit"></i>
                                                </span>
                                                <span class="navi-text">Refund</span>
                                            </a>
                                         </li>
                                         @elseif($d->status === 'refunded')
                                          <li class="navi-item">
                                            <a href="#" class="navi-link">
                                                <span class="navi-icon">
                                                    <i class="la la-edit"></i>
                                                </span>
                                                <span class="navi-text">Refunded</span>
                                            </a>
                                         </li>
                                         @endif                                               
                                         
                                         @elseif(Auth::guard('seller')->check())
                                           <li class="navi-item">
                                            <a href="{{ route('dispute.show.seller',$d->id)}}" class="navi-link">
                                                <span class="navi-icon">
                                                    <i class="la la-edit"></i>
                                                </span>
                                                <span class="navi-text">View</span>
                                            </a>
                                         </li>
        
                                           @endif 





                                    </ul>
                                </div>
                            </div>
                        </span>
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>
</div>


@endsection

{{-- Styles Section --}}
@section('styles')

@endsection

@section('scripts')
<script src="{{ asset('plugins/custom/datatables/datatables.bundle.js?v=7.0.4') }}" type="text/javascript"></script>
<script>
    var table = $('#kt_datatable');

    // begin first table
    table.DataTable({
        // DOM Layout settings
        dom: "<'row py-3'<'col-sm-12 col-md-6'l><'col-sm-12 col-md-6'f>>" +
            "<'row'<'col-sm-12 col-md-6'i><'col-sm-12 col-md-6'p>>" +
            "<'row py-3'<'col-sm-12'tr>>" +
            "<'row py-3'<'col-sm-12 col-md-6'l><'col-sm-12 col-md-6'f>>" +
            "<'row'<'col-sm-12 col-md-5'i><'col-sm-12 col-md-7'p>>", // read more: https://datatables.net/examples/basic_init/dom.html

        columnDefs: [{
            targets: -1
            , title: 'Actions'
            , orderable: false,

        }]
    , });

</script>
@endsection